#pragma once

#include <memory>
#include <string>
#include <vector>

#include "state.hpp"

/**
 * @brief Discrete motion command used by the local planner.
 *
 * Stores the linear and angular increments that a kinematic model can roll out
 * from a given vehicle state.
 *
 * @return --
 * @note Ackermann primitives use steering_angle; differential primitives use angular_step.
 */
struct MotionPrimitive {
  double linear_step{0.0};
  double angular_step{0.0};
  double steering_angle{0.0};
  bool in_place_rotation{false};
};

/**
 * @brief Result of simulating a motion primitive.
 *
 * Contains the intermediate vehicle states generated by applying one primitive
 * for a fixed number of rollout steps.
 *
 * @return --
 * @note The last sample is the end state used as the child node in the planner tree.
 */
struct RolloutResult {
  std::vector<State> samples;
};

/**
 * @brief Configuration parameters for the Ackermann kinematic model.
 *
 * Defines the wheelbase, steering limit and linear displacement used to build
 * Ackermann motion primitives and rollouts.
 *
 * @return --
 * @note wheelbase and linear_step must be greater than zero.
 */
struct AckermannKinematicsConfig {
  double wheelbase{0.0};
  double max_steering_angle{0.0};
  double linear_step{0.0};
};

/**
 * @brief Configuration parameters for the differential kinematic model.
 *
 * Defines the forward displacement, angular increment range, number of angular
 * samples and whether pure in-place rotations are available.
 *
 * @return --
 * @note linear_step must be greater than zero and max_angular_step must be non-negative.
 */
struct DifferentialKinematicsConfig {
  double linear_step{0.0};
  double max_angular_step{0.0};
  int moving_angular_samples{0};
  bool include_in_place_rotation{true};
};

/**
 * @brief Common interface for kinematic models used by the local planner.
 *
 * Allows path_planning to use Ackermann or differential motion models through
 * the same rollout, cost and primitive-generation API.
 *
 * @return --
 * @note This is an abstract base class; instantiate one of the concrete models instead.
 */
class KinematicModel {
public:
  /**
   * @brief Destroy the kinematic model through the base interface.
   *
   * Enables correct cleanup when a concrete model is stored in a KinematicModel pointer.
   *
   * @return --
   * @note Required because the planner stores models through std::unique_ptr<KinematicModel>.
   */
  virtual ~KinematicModel() = default;

  /**
   * @brief Build the discrete motion primitives available to the planner.
   *
   * Creates the candidate movements that the A* tree can expand from each node.
   *
   * @param branching_factor Requested number of movement branches.
   * @return Vector of motion primitives.
   * @note Concrete models may clamp or override the requested branching factor.
   */
  [[nodiscard]] virtual std::vector<MotionPrimitive> buildMotionPrimitives(int branching_factor) const = 0;

  /**
   * @brief Simulate one primitive from a start state.
   *
   * Applies the provided primitive for a fixed number of samples and returns the
   * generated intermediate states.
   *
   * @param start Initial vehicle state.
   * @param primitive Motion primitive to simulate.
   * @param steps Number of rollout samples to generate.
   * @return Rollout result containing sampled states.
   * @note The rollout does not perform collision checking.
   */
  [[nodiscard]] virtual RolloutResult rollout(const State &start, const MotionPrimitive &primitive, int steps) const = 0;

  /**
   * @brief Compute the effort cost of a primitive.
   *
   * Returns a scalar penalty used by the planner to prefer simpler movements.
   *
   * @param primitive Motion primitive to evaluate.
   * @return Effort penalty.
   * @note The meaning of effort depends on the concrete model.
   */
  [[nodiscard]] virtual double controlEffort(const MotionPrimitive &primitive) const = 0;

  /**
   * @brief Compute the transition smoothness cost between primitives.
   *
   * Penalizes abrupt changes between a previous primitive and the current one.
   *
   * @param previous Previous primitive, or nullptr for the root transition.
   * @param current Current primitive.
   * @return Smoothness penalty.
   * @note Used by the planner to reduce sharp changes in command direction.
   */
  [[nodiscard]] virtual double smoothnessCost(const MotionPrimitive *previous, const MotionPrimitive &current) const = 0;

  /**
   * @brief Return the maximum forward displacement per rollout sample.
   *
   * Provides a lower-bound estimate helper for the A* search.
   *
   * @return Maximum forward step in meters.
   * @note This value is used for planning heuristics, not for collision checking.
   */
  [[nodiscard]] virtual double maxForwardStep() const = 0;
};

/**
 * @brief Ackermann steering kinematic model.
 *
 * Generates steering-angle primitives and rolls them out using a bicycle-style
 * forward motion approximation.
 *
 * @return --
 * @note This model does not support in-place rotation.
 */
class AckermannKinematicModel final : public KinematicModel {
public:
  /**
   * @brief Create an Ackermann kinematic model.
   *
   * Stores and validates the Ackermann configuration.
   *
   * @param config Ackermann kinematic parameters.
   * @return --
   * @note Throws std::invalid_argument if wheelbase or linear_step are invalid.
   */
  explicit AckermannKinematicModel(const AckermannKinematicsConfig &config);
  [[nodiscard]] std::vector<MotionPrimitive> buildMotionPrimitives(int branching_factor) const override;
  [[nodiscard]] RolloutResult rollout(const State &start, const MotionPrimitive &primitive, int steps) const override;
  [[nodiscard]] double controlEffort(const MotionPrimitive &primitive) const override;
  [[nodiscard]] double smoothnessCost(const MotionPrimitive *previous, const MotionPrimitive &current) const override;
  [[nodiscard]] double maxForwardStep() const override;

private:
  AckermannKinematicsConfig config_;
};

/**
 * @brief Differential drive kinematic model.
 *
 * Generates angular-step primitives and optionally adds pure in-place rotations.
 *
 * @return --
 * @note This model uses angular_step instead of steering_angle.
 */
class DifferentialKinematicModel final : public KinematicModel {
public:
  /**
   * @brief Create a differential kinematic model.
   *
   * Stores and validates the differential configuration.
   *
   * @param config Differential kinematic parameters.
   * @return --
   * @note Throws std::invalid_argument if linear_step or max_angular_step are invalid.
   */
  explicit DifferentialKinematicModel(const DifferentialKinematicsConfig &config);
  [[nodiscard]] std::vector<MotionPrimitive> buildMotionPrimitives(int branching_factor) const override;
  [[nodiscard]] RolloutResult rollout(const State &start, const MotionPrimitive &primitive, int steps) const override;
  [[nodiscard]] double controlEffort(const MotionPrimitive &primitive) const override;
  [[nodiscard]] double smoothnessCost(const MotionPrimitive *previous, const MotionPrimitive &current) const override;
  [[nodiscard]] double maxForwardStep() const override;

private:
  DifferentialKinematicsConfig config_;
};

/**
 * @brief Create a concrete kinematic model from a model name.
 *
 * Selects the configured model implementation and returns it through the common
 * KinematicModel interface.
 *
 * @param model_name Model name, currently "ackermann" or "differential".
 * @param ackermann_config Configuration used when model_name is "ackermann".
 * @param differential_config Configuration used when model_name is "differential".
 * @return Unique pointer to the selected kinematic model.
 * @note Throws std::invalid_argument for unsupported model names.
 */
std::unique_ptr<KinematicModel> makeKinematicModel(const std::string &model_name, const AckermannKinematicsConfig &ackermann_config, const DifferentialKinematicsConfig &differential_config);
